swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <h1>test></h1><img onerror=alert('textarea') src=1><img src=x onerror=eval(alert(1))><textarea><path id="</textarea><img/src=x onError=`${x}`;alert(`Ex.Mi`);>">
