swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><p onmouseover="alert('xss');">xss</p>">


  version: production
