swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>

  version: production
