swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    123123<h1>123</h1><svg onloads=><img src=x b=1 c=1 donerrora=confirm() onerror=confirm(1)> 

  version: production
